"""
PlantUML diagram generators for SWE.2 architectural design.

Produces two diagrams:
  component_diagram.puml   — full static component + interface view
  safety_diagram.puml      — safety-layer focused view with FFI notes
"""

from swe1.models import ASIL
from .models import SwComponent

_ASIL_PUML_COLOR = {
    ASIL.D: "#ffcccc",
    ASIL.C: "#ffe0cc",
    ASIL.B: "#fff3cc",
    ASIL.A: "#f0f5cc",
    ASIL.QM: "#e0f5e0",
}

_LAYER_BG = {
    "application": "#ddeeff",
    "safety":      "#fff8e8",
    "security":    "#f8eeff",
}

_LAYER_TITLE = {
    "application": "Application Layer",
    "safety":      "Safety Layer",
    "security":    "Security Layer",
}


def _alias(name: str) -> str:
    """Strip non-alphanumeric chars for a valid PlantUML alias."""
    return "".join(c for c in name if c.isalnum())


def _comp_label(comp: SwComponent) -> str:
    asil_tag = comp.asil.value
    cybersec_tag = " | CYBERSEC" if comp.cybersecurity_relevant else ""
    return f"[{comp.name}]\\n<<{asil_tag}{cybersec_tag}>>"


def render_component_diagram(
    components: list[SwComponent], project_key: str, metadata: dict
) -> str:
    app_comps = [c for c in components if c.layer == "application"]
    saf_comps = [c for c in components if c.layer == "safety"]
    sec_comps = [c for c in components if c.layer == "security"]
    has_safety  = bool(saf_comps)
    has_security = bool(sec_comps)

    lines = [
        "@startuml",
        f"' AutoPragma SWE.2 — Software Component Diagram",
        f"' Project : {project_key}",
        f"' Source  : {metadata.get('document_id', 'SwRS')} v{metadata.get('version', '?')}",
        f"' Generated by AutoPragma SWE.2 pipeline",
        "",
        "skinparam componentStyle rectangle",
        "skinparam backgroundColor white",
        "skinparam defaultFontName Arial",
        "skinparam shadowing false",
        "skinparam component {",
        "  BorderColor #555555",
        "  FontStyle bold",
        "}",
        "skinparam package {",
        "  BorderColor #888888",
        "  FontStyle bold",
        "}",
        "",
    ]

    # Application layer
    if app_comps:
        lines += [f'package "Application Layer" <<Frame>> {_LAYER_BG["application"]} {{']
        for c in app_comps:
            color = _ASIL_PUML_COLOR.get(c.asil, "#ffffff")
            lines.append(f'  component "{_comp_label(c)}" as {_alias(c.name)} {color}')
        lines += ["}", ""]

    # Safety layer
    if has_safety:
        lines += [f'package "Safety Layer" <<Frame>> {_LAYER_BG["safety"]} {{']
        for c in saf_comps:
            color = _ASIL_PUML_COLOR.get(c.asil, "#ffffff")
            lines.append(f'  component "{_comp_label(c)}" as {_alias(c.name)} {color}')
        lines += ["}", ""]

    # Security layer
    if has_security:
        lines += [f'package "Security Layer" <<Frame>> {_LAYER_BG["security"]} {{']
        for c in sec_comps:
            lines.append(f'  component "{_comp_label(c)}" as {_alias(c.name)} #f3e8fd')
        lines += ["}", ""]

    # AUTOSAR BSW package — show only modules actually needed
    bsw_modules = ["RTE"]
    if has_safety:
        bsw_modules += ["DEM", "FIM", "WdgM"]
    if has_security:
        bsw_modules += ["Csm", "NvM"]

    lines += ['package "AUTOSAR BSW" <<Frame>> #f0f0f0 {']
    for mod in bsw_modules:
        lines.append(f'  component "[{mod}]" as {mod} #e0e0e0')
    lines += ["}", ""]

    lines.append("' ── Interface connections ──")

    # Application → RTE
    for c in app_comps:
        lines.append(f"{_alias(c.name)} -down-> RTE : <<R-Port>>")

    # SafetyMonitor → BSW
    for c in saf_comps:
        a = _alias(c.name)
        lines.append(f"{a} -down-> DEM  : <<DTC store>>")
        lines.append(f"{a} -down-> FIM  : <<fault flag>>")
        lines.append(f"{a} -down-> WdgM : <<alive kick>>")

    # SecManager → BSW
    for c in sec_comps:
        a = _alias(c.name)
        lines.append(f"{a} -down-> Csm : <<crypto ops>>")
        lines.append(f"{a} -down-> NvM : <<audit log>>")

    lines.append("")
    lines.append("' ── Cross-cutting relationships ──")

    # Safety monitors application components
    for c in saf_comps:
        for target in c.monitors:
            lines.append(f"{_alias(c.name)} ..> {_alias(target)} : <<monitors>>")

    # Security secures application components
    for c in sec_comps:
        for target in c.secures:
            lines.append(f"{_alias(c.name)} ..> {_alias(target)} : <<secures>>")

    lines += ["", "@enduml"]
    return "\n".join(lines)


def render_safety_diagram(
    components: list[SwComponent], project_key: str, metadata: dict
) -> str:
    saf_comps = [c for c in components if c.layer == "safety"]
    app_comps = [c for c in components if c.layer == "application"]

    if not saf_comps:
        # No safety-rated items — return a minimal placeholder
        return "\n".join([
            "@startuml",
            f"' AutoPragma SWE.2 — Safety Architecture View",
            f"' Project: {project_key}",
            "",
            'note as N',
            "  No ASIL-rated software requirements in this specification.",
            "  Safety architecture diagram not applicable.",
            "end note",
            "",
            "@enduml",
        ])

    saf = saf_comps[0]
    monitored = [c for c in app_comps if c.name in saf.monitors]

    # Determine highest monitored ASIL for notes
    all_asils = [saf.asil] + [c.asil for c in monitored]
    highest = saf.asil

    lines = [
        "@startuml",
        f"' AutoPragma SWE.2 — Safety Architecture View",
        f"' Project : {project_key}",
        f"' Standard: ISO 26262-6 §7.4.14 (Freedom from Interference)",
        f"' Generated by AutoPragma SWE.2 pipeline",
        "",
        "skinparam backgroundColor white",
        "skinparam defaultFontName Arial",
        "skinparam shadowing false",
        "skinparam component {",
        "  BorderColor #555555",
        "  FontStyle bold",
        "}",
        "skinparam package {",
        "  BorderColor #aa8800",
        "  FontStyle bold",
        "}",
        "",
        f'package "ASIL Partition [{saf.asil.value}]" <<Rectangle>> #fff8e8 {{',
        f'  component "[{saf.name}]\\n<<{saf.asil.value}>>\\nOS App: Safety_OsApp" as SAF {_ASIL_PUML_COLOR.get(saf.asil, "#fff3cc")}',
        "  note right of SAF",
        "    SW Safety Mechanisms:",
        "    - Alive supervision (MCWDT / WdgM)",
        "    - Deadline supervision (WdgM)",
        "    - Logical supervision (graph)",
        "    Fault reaction:",
        "    - DTC storage via AUTOSAR DEM",
        "    - Inhibition via FIM",
        f"    - Safe state within FTTI (HARA-derived)",
        f"    Ref: ISO 26262-6 Table 8",
        "  end note",
        "}",
        "",
    ]

    if monitored:
        lines += [
            'package "Application Partition" <<Rectangle>> #e8f4fd {',
        ]
        for c in monitored:
            color = _ASIL_PUML_COLOR.get(c.asil, "#e0f5e0")
            lines.append(f'  component "[{c.name}]\\n<<{c.asil.value}>>" as {_alias(c.name)} {color}')
        lines += ["}", ""]

    lines += [
        'package "AUTOSAR Safety BSW" <<Rectangle>> #f0f0f0 {',
        '  component "[WdgM]" as WdgM #e0e0e0',
        '  component "[DEM]"  as DEM  #e0e0e0',
        '  component "[FIM]"  as FIM  #e0e0e0',
        "}",
        "",
    ]

    for c in monitored:
        lines.append(f"SAF ..> {_alias(c.name)} : <<monitors\\ndetect + react>>")

    lines += [
        "SAF -down-> WdgM : <<alive supervision>>",
        "SAF -down-> DEM  : <<DTC report>>",
        "SAF -down-> FIM  : <<fault inhibition>>",
        "",
        "note bottom",
        "  Freedom from Interference (FFI) enforced by:",
        "  1. AUTOSAR OS Applications (memory partitioning)",
        "  2. TRAVEO T2G SMPU / PPU (hardware memory protection)",
        "  3. E2E protection on safety-relevant inter-component interfaces",
        "  Ref: ISO 26262-6 §7.4.14 | AUTOSAR_SWS_SafetyExtensions",
        "end note",
        "",
        "@enduml",
    ]

    return "\n".join(lines)
