"""
PlantUML class diagram generator for SWE.3 software detailed design.

Produces one diagram per SW component showing its decomposed units,
their provided interfaces, internal data, and intra-component
dependencies.  All units within a component are rendered inside a
package that carries the component name and ASIL classification.
"""

from swe1.models import ASIL
from swe2.models import SwComponent

from .models import SwUnit, UnitLink

_ASIL_COLOR = {
    ASIL.D:  "#ffcccc",
    ASIL.C:  "#ffe0cc",
    ASIL.B:  "#fff3cc",
    ASIL.A:  "#f0f5cc",
    ASIL.QM: "#e0f5e0",
}
_LAYER_BG = {
    "application": "#ddeeff",
    "safety":      "#fff8e8",
    "security":    "#f8eeff",
}

_LAYER_STEREOTYPE = {
    "application": "<<Application>>",
    "safety":      "<<SafetyMechanism>>",
    "security":    "<<SecurityService>>",
}


def _alias(name: str) -> str:
    return "".join(c for c in name if c.isalnum())


def render_detailed_design(
    components: list[SwComponent],
    units: list[SwUnit],
    links: list[UnitLink],
    project_key: str,
    metadata: dict,
) -> str:
    units_by_comp: dict[str, list[SwUnit]] = {}
    for u in units:
        units_by_comp.setdefault(u.component_id, []).append(u)

    dep_links = [lnk for lnk in links if lnk.link_type == "depends"]

    lines = [
        "@startuml",
        f"' AutoPragma SWE.3 — Software Detailed Design",
        f"' Project : {project_key}",
        f"' Source  : {metadata.get('document_id', 'SwRS')} v{metadata.get('version', '?')}",
        f"' Generated by AutoPragma SWE.3 pipeline",
        "",
        "skinparam classAttributeIconSize 0",
        "skinparam backgroundColor white",
        "skinparam defaultFontName Arial",
        "skinparam shadowing false",
        "skinparam class {",
        "  BorderColor #555555",
        "  HeaderBackgroundColor #dddddd",
        "  FontStyle bold",
        "}",
        "skinparam package {",
        "  BorderColor #888888",
        "  FontStyle bold",
        "}",
        "",
    ]

    for comp in components:
        comp_units = units_by_comp.get(comp.id, [])
        if not comp_units:
            continue

        bg    = _LAYER_BG.get(comp.layer, "#f5f5f5")
        stereo = _LAYER_STEREOTYPE.get(comp.layer, "")
        asil_tag = comp.asil.value
        cyber_tag = " | CYBERSEC" if comp.cybersecurity_relevant else ""

        lines += [
            f'package "{comp.name} [{asil_tag}{cyber_tag}] {stereo}" <<Rectangle>> {bg} {{',
        ]

        for u in comp_units:
            unit_color = _ASIL_COLOR.get(u.asil, "#ffffff")
            lines += [
                f"  class \"{u.name}\" as {_alias(u.name)} {unit_color} {{",
            ]
            # Provided operations (public)
            for op in u.interface.provided:
                params = ", ".join(op.parameters)
                lines.append(f"    + {op.name}({params}) : {op.return_type}")
            # Internal data (private)
            if u.internal_data:
                lines.append("    --")
                for datum in u.internal_data:
                    lines.append(f"    - {datum}")
            lines.append("  }")

        lines += ["}", ""]

    # Intra-component dependency arrows
    if dep_links:
        lines.append("' ── Unit dependencies ──")
        unit_id_to_name = {u.id: u.name for u in units}
        for lnk in dep_links:
            src = _alias(unit_id_to_name.get(lnk.component_id, lnk.component_id))
            tgt = _alias(unit_id_to_name.get(lnk.unit_id, lnk.unit_id))
            lines.append(f"{src} --> {tgt}")
        lines.append("")

    lines += ["@enduml"]
    return "\n".join(lines)
